config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :exhibits
  resources :groups
  resources :articles

  namespace :admin do
    resources :users
    resources :exhibits
    resources :groups
    resources :articles
  end

end

app/models/exhibit.rb
# == Schema Information
#
# Table name: exhibits
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  section              :string
#  collection_number    :string
#  inventory_number     :string
#  another_inv_num      :string
#  photo_number         :string
#  dating               :string
#  material             :string
#  size_or_weight       :string
#  condition            :string
#  renewal              :boolean
#  date_of_renewal      :string
#  storage_location     :string
#  locality             :string
#  coordinates          :string
#  museum_director      :string
#  custodian            :string
#  notes                :text
#  date_of_receipt      :string
#  act_of_reception_num :string
#  user_id              :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  photo                :string
#  group_id             :integer
#

class Exhibit < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mount_uploader :photo, PhotoUploader

  belongs_to :group
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  searchkick

  def as_indexed_json(options={})
    as_json(
      only: [:name, :group_id, :description, :section,
             :collection_number, :inventory_number,
             :another_inv_num, :photo_number, :dating, :material,
             :size_or_weight, :condition, :renewal, :date_of_renewal, :address, :coordinates, :notes,
             :storage_location, :locality, :museum_director, :custodian,
             :date_of_receipt, :act_of_reception_num]
    )
  end
end

app/controllers/admin/exhibits_controller.rb
class Admin::ExhibitsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :only_admin!
  before_filter :find_exhibit, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @exhibits = Exhibit.all
    @exhibits = @exhibits.where("LOWER(name) LIKE LOWER('%#{params[:q]}%')") if params[:q].present?
  end

  def show
  end

  def new
    @exhibit = 	Exhibit.new
  end

  def create
    @exhibit = Exhibit.new(page_params)
    @exhibit.user = current_user
    if @exhibit.save
      redirect_to admin_exhibits_path
    else
      puts @exhibit.errors.full_messages.inspect
      render :new
    end
  end

  def edit
  end

  def update
    if @exhibit.update(page_params)
      redirect_to admin_exhibit_path(@exhibit)
    else
      render :edit
    end
  end

  def destroy
    if @exhibit.destroy
      redirect_to  admin_groups_path
    else
      redirect_to  admin_groups_path, flash: {error: 'Something went wrong'}
    end
  end

  private

  def only_admin!
    unless current_user.role == 'admin'
      redirect_to groups_path, flash: {error: 'Тільки адміністратор має доступ до цього розділу'}
    end
  end

  def page_params
    params.require(:exhibit).permit(:name, :group_id, :description, :section,
                                    :collection_number, :inventory_number,
                                    :another_inv_num, :photo, :photo_number, :dating, :material,
                                    :size_or_weight, :condition, :renewal, :date_of_renewal, :address, :coordinates, :notes,
                                    :storage_location, :locality, :museum_director, :custodian,
                                    :date_of_receipt, :act_of_reception_num)
  end

  def find_exhibit
    @exhibit = Exhibit.find(params[:id])
  end

end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_filter :find_exhibit, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_filter :only_admin!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @exhibit = 	Exhibit.new
  end

  def create
    @exhibit = Exhibit.new(page_params)
    @exhibit.user = current_user
    if @exhibit.save
      redirect_to exhibit_path(@exhibit)
    else
      puts @exhibit.errors.full_messages.inspect
      render :new
    end
  end

  def index
    @exhibits = Exhibit.all.reindex
    #@exhibits = @exhibits.where("LOWER(name) LIKE LOWER('%#{params[:q]}%')") if params[:q].present?
    @exhibits = Exhibit.search((params[:q].present? ? params[:q] : '*')).records if params[:q].present?
  end

  def edit
  end

  def update
    if @exhibit.update(page_params)
      redirect_to exhibit_path(@exhibit)
    else
      render :edit
    end
  end

  def show
    @title = "#{@exhibit.name} : #{@exhibit.group.name} - Музей «Мостищина»"
  end

  def destroy
    if @exhibit.destroy
      redirect_to  groups_path
    else
      redirect_to  groups_path, flash: {error: 'Something went wrong'}
    end
  end

  private

  def only_admin!
    unless current_user.role == 'admin'
      redirect_to groups_path, flash: {error: 'Only admin can update exhibit'}
    end
  end

  def page_params
    params[:exhibit].permit(:name, :group_id, :description, :section,
                            :collection_number, :inventory_number,
                            :another_inv_num, :photo, :photo_number, :dating, :material,
                            :size_or_weight, :condition, :renewal, :date_of_renewal, :address, :coordinates, :notes,
                            :storage_location, :locality, :museum_director, :custodian,
                            :date_of_receipt, :act_of_reception_num)
  end

  def find_exhibit
    @exhibit = Exhibit.find(params[:id])
  end
end

app/helpers/admin/exhibits_helper.rb
module Admin::ExhibitsHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/_form.html.slim
= simple_form_for(@exhibit) do |f|
  = f.error_notification

  = f.input :name, label: 'Назва:'
  = f.label 'Фондова група: '
  br
  = f.collection_select :group_id, Group.order(:name), :id, :name, label: 'Фондова група:'
  br
  br
  = f.input :description, :input_html => {:style=> 'height: 200px'}, label: 'Опис:'
  = f.input :section, label: 'Розділ:'
  = f.input :collection_number, label: 'Номер колекції:'
  = f.input :inventory_number, label: 'Інвентарний номер'
  = f.input :another_inv_num, label: 'Інший інвентарний номер'
  = f.label "Фото: "
  = f.file_field :photo, label: 'Фото'
  br
  = f.input :photo_number, label: 'Номер фотографії'
  = f.input :dating, label: 'Датування'
  = f.input :material, label: 'Матеріал'
  = f.input :size_or_weight, label: 'Розмір/вага'  
  = f.input :condition, label: 'Стан'
  = f.input :renewal, as: :boolean, label: 'Реставрація/консервація'
  = f.input :date_of_renewal, label: 'Дата реставрації/консервації'
  = f.input :storage_location, label: 'Місце зберігання'
  = f.input :locality, label: 'Місцевість'
  = f.input :address, label: 'Aдреса'
  = f.input :museum_director, label: 'Директор музею'
  = f.input :custodian, label: 'Зберігач фондів'
  = f.input :date_of_receipt, label: 'Дата прийому'
  = f.input :act_of_reception_num, label: 'Номер акту прийому'
  = f.input :notes, label: 'Примітки', :input_html => {:style=> 'height: 200px'}
  = f.button :submit, value: 'Зберегти'
div#gmaps-error

javascript:

  $(function(){
    $("#exhibit_address").geocomplete();

    if (window.location.href.slice(-3) === 'new') {
      $('.exhibit_date_of_renewal').hide()
      $('#exhibit_renewal').click(function(){
        $('.exhibit_date_of_renewal').toggle('fast');
      })
    }	
  })

app/views/exhibits/edit.html.slim
div.container
  div.row.box
    div.col-md-2
    div.col-md-8
      h1.text-center
        | Редагувати експонат
      = render 'form'  

app/views/exhibits/index.html.slim
  div.container
		div.row
			div.col-md-2
				| Navigation bar
			div.col-md-8
        - @exhibits.each do |exh|
          a href="#{exhibit_path(exh)}"
            div.exhibit-preview
              h4
                = link_to exh.name, exh
              p
                = exh.description
              div
                - if exh.photo.present?
                  = image_tag exh.photo.url(:thumb)
                - else   
                  = image_tag "default_photo.jpg"

				

app/views/exhibits/new.html.slim
div.container
  div.row.box
    div.col-md-2
    div.col-md-8
      h1.text-center
        | Додати експонат
      = render 'form'  

app/views/exhibits/show.html.slim
div.container.box
  div.row
    div.col-md-6.exh-desc-field
      div.row
        div.col-md-1
          = link_to '', @exhibit.group, class: 'glyphicon glyphicon-arrow-left back-button'
        div.col-md-10.text-center
          h4 = @exhibit.name
        div.col-md-1
          = link_to '', edit_exhibit_path(@exhibit), class: 'glyphicon glyphicon-pencil exh-edit-btn' if user_signed_in?
          = link_to '', exhibit_path(@exhibit), method: :delete, data: { confirm: "Ви впевнені, що хочете видалити експонат #{@exhibit.name}? Цю дію неможливо буде скасувати."}, class: 'glyphicon glyphicon-trash exh-edit-btn' if user_signed_in?  
      div.row
        div.col-md-6
          p.exh-field 
            | Розділ: 
          p.text-capitalize = link_to @exhibit.group.name, @exhibit.group
          p.exh-field 
            | Матеріал: 
          p.text-capitalize 
            = @exhibit.material
          p.exh-field
            | Стан збереження:
          p.text-capitalize
            = @exhibit.condition            
        div.col-md-6
          p.exh-field
            | Датування: 
          p
            = @exhibit.dating
          p.exh-field 
            | Розмір/вага: 
          p
            = @exhibit.size_or_weight
          p.exh-field 
            | Реставрація/Консерація:
          - if @exhibit.renewal == true
            p.glyphicon.glyphicon-ok
          - else 
            p.glyphicon.glyphicon-minus
        div.row
          div.col-md-12.exh-desc-field
            p.exh-field.text-center 
              | Опис: 
            p = @exhibit.description
        div.row
          div.col-md-6.exh-desc-field
            p.exh-field 
              | № колекції: 
            p.text-uppercase 
              = @exhibit.collection_number
            p.exh-field
              | № фотографії
            p.text-uppercase
              = @exhibit.photo_number
            p.exh-field
              | № акту прийому
            p.text-uppercase
              = @exhibit.act_of_reception_num
            p.exh-field
              | Місце зберігання:
            p.text-capitalize
              = @exhibit.storage_location                        
          div.col-md-6
            p.exh-field
              | Інвентарний №
            p.text-uppercase 
              = @exhibit.inventory_number
            p.exh-field
              | Інший інвентарний №
            p.text-uppercase
              = @exhibit.another_inv_num
            p.exh-field
              | Дата прийому:
            p.text-uppercase
              = @exhibit.date_of_receipt
            p.exh-field
              | Дата реставрації/консервації:
            p.text-uppercase
              = @exhibit.date_of_renewal        
        div.row
          div.col-md-12.exh-desc-field
            p.exh-field.text-center 
              | Примітки: 
            p = @exhibit.notes 

    div.col-md-6.photo-block
      - if @exhibit.photo.present?
        img#myImg.exh-photo-zoomed src="#{@exhibit.photo.url(:big)}" data-zoom-image="#{@exhibit.photo.url}" alt="#{@exhibit.name}"
      - else
        = image_tag("default_photo.jpg", id: "myImg", class: "exh-photo-zoomed")  
      #myModal.modal
        span.close onclick="document.getElementById('myModal').style.display='none'"  ×
        img#img01.modal-content
        #caption
          = @exhibit.name

      br
      .glyphicon.glyphicon-map-marker
      p = " #{@exhibit.address}"
      iframe#map allowfullscreen="" frameborder="0" height="450" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyChJvkG27cUdouHAr4iqFQi6WxF_G5eoZI&q=#{@exhibit.address}" style="border:0" width="600"

javascript:
  
  $(function(){
    $('.exh-photo-zoomed').elevateZoom({
      zoomType: 'lens',
      lensShape: 'round',
      lensSize: 200,
      scrollZoom : true
    });

    var modal = $('#myModal');
    var img = $('#myImg');
    var modalImg = $('#img01');
    var captionText = $('#caption');
    img.click(function(){
        modal.css('display', 'block');
        modalImg.attr("src", this.src);
        captionText.innerHTML = this.alt;
    })

    var span = $('.close')[0];
    span.click(function() { 
      modal.css("display" ,"none")
    })
  })