config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :exhibits
  resources :groups
  resources :articles

  namespace :admin do
    resources :users
    resources :exhibits
    resources :groups
    resources :articles
  end

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  ancestry    :string
#  photo       :string
#

class Group < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :exhibits
  validates :name, presence: true
  has_ancestry
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :only_admin!, only: [:edit, :update, :destroy]
  before_filter :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.roots
    redirect_to admin_exhibits_path if params[:q].present?
  end

  def show
    @exhibits = Exhibit.where(group_id: [@group.subtree_ids]).page(params[:page]).per(10)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to admin_group_path(@group)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      redirect_to admin_group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def only_admin!
    unless current_user.role == 'admin'
      redirect_to groups_path, flash: {error: 'Тільки адміністратор має доступ до цього розділу'}
    end
  end

  def group_params
    params.require(:group).permit(:name, :parent_id, :photo, :description)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #before_action :only_author!, only: [:edit, :update, :destroy]

  def index
    @groups = Group.roots
    redirect_to exhibits_path if params[:q].present?
    @title = "Фонди - Музей «Мостищина»"
  end

  def show
    @exhibits = Exhibit.where(group_id: [@group.subtree_ids]).page(params[:page]).per(10)
    @title = "#{@group.name} : #{@group.parent.name if @group.parent.present?} - Музей «Мостищина»"
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  protected

  def set_group
    @group = Group.find(params[:id])
  end

  def only_author!
    unless @group.user_id == current_user.id
      redirect_to groups_path, flash: {error: 'Only author can update exhibit'}
    end
  end

  def group_params
    params.require(:group).permit(:name, :parent_id, :photo, :description)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
	def next_element(index)
		if index != @groups.size - 1
			index = index + 1
		else
			index = 0		
		end
		index
	end

	def build_breadcrumbs(group)
		result = []
    group.ancestors.each do |ancestor|
    	result << content_tag(:li, class: "breadcrumb-item") do 
    		link_to(ancestor.name, ancestor)
    	end
    end
    result << content_tag(:li, group.name, class: "breadcrumb-item-active")
    result.join('').html_safe
	end
end

app/views/groups/_footer_groups.html.slim
ul
  li
    = link_to 'Головна', root_path
  li
    = link_to 'Фонди', groups_path
ul    
  li
    = link_to 'Новини', articles_path
  li
    = link_to 'Контакти', page_path('contact')

  

app/views/groups/_form.html.slim
div.container
  div.row.box
    div.col-md-2
    div.col-md-8
      h1.text-center
        | Редагувати фондову групу
div.container
	div.row.box
		div.col-md-3
		div.col-md-6
			= simple_form_for(@group) do |f|
			  = f.error_notification

			  = f.input :name, label: 'Назва:'
			  = f.label 'Батьківська фондова група: '
			  = f.collection_select :parent_id, Group.where("id != #{@group.id}").order(:name), :id, :name, {include_blank: true}
			  br
			  br
			  = f.input :description, label: 'Опис'
			  = f.label 'Фото'
			  = f.file_field :photo
			  br
			  = f.button :submit, value: 'Зберегти'  

app/views/groups/edit.html.slim
= render 'form'

app/views/groups/index.html.slim
div.container  
  .row
    .box
      .col-lg-12
        hr
        h3.intro-text.text-center
          | Фонди
        hr
        img.img-responsive.img-border.img-left style="width: 300px" alt="" src=asset_path('intro4.jpg')
        p 
          | Фонди налічують 1855 одиниць збережень. В експозиції першої кімнати — пам'ятки археології. У другій — експозиція про діячів легіону Українських Січових Стрільців Галичини, національно-визвольні змагання у краї. У центральній кімнаті представлено старовинні меблі, речі, картини, 300 книжок рідкісних видань, зброю та ін. 
        p
          | У музеї зберігаються мистецькі твори, речі побуту, археологічні знахідки, нумізматика, матеріали (документи, щоденники) про рідний край, давня література, інформація про видатних людей Мостищини. Значну цінність становлять картини видатної художниці Олени Кульчицької, знайдені в селах Малнів і Черневе. 
div.container.slideshow-wrapper
  div.col-md-12.slideshow-wrapper-inner
    /h1 Bootstrap 3 Thumbnail Slider
    div.well
      #myCarousel.carousel.slide
        /! Carousel items
        .carousel-inner
          - @groups.each_with_index do |group, i|
            div.item
              a href="#{group_path(group)}"
                div.col-md-3.slide-side
                  div.pr-group-title
                    = @groups[i-1].name
                  = image_tag @groups[i-1].photo.url(:small), class: 'prev-group-img' if @groups[i-1].photo.present?
                div.group-photo-block.col-md-3
                  = image_tag group.photo.url(:thumb), class: 'current-img-group' if group.photo.present?
                div.group-description-block.col-md-3  
                  h4
                    = group.name
                  p  
                    = group.description
                  p.group-counter
                    = "#{i+1}/#{@groups.size}"
                div.col-md-3.slide-side
                  div.next-group-title
                    = @groups[next_element(i)].name
                  = image_tag @groups[next_element(i)].photo.url(:small), class: 'next-group-img' if @groups[next_element(i)].photo.present?
              br
              div.edit-buttons
                = link_to '', new_group_path, class: 'glyphicon glyphicon-plus' if user_signed_in?
                br
                br      
                = link_to '', edit_group_path(group), class: 'glyphicon glyphicon-pencil' if user_signed_in?
                br
                br
                = link_to '', group_path(group), method: :delete, data: { confirm: "Ви впевнені, що хочете видалити фондову групу #{group.name}? Цю дію неможливо буде скасувати."}, class: 'glyphicon glyphicon-trash' if user_signed_in?      
               
        a.left.carousel-control.groups-carousel data-slide="prev" href="#myCarousel"
        a.right.carousel-control.groups-carousel data-slide="next" href="#myCarousel"
            
javascript:

  $(document).ready(function() {
    $('.item:first').addClass('active');
    $('#myCarousel').carousel({
    interval: 2000
    })
  });

  $('.item').click(function(){
    $('.item').removeClass('active');
    setTimeout(function(){  
      $('.item:first').addClass('active');
    }, 300);
  });

app/views/groups/new.html.slim
div.container
	div.row
		div.col-md-3
		div.col-md-6.text-center
		  h3
		    | Нова фондова група
div.container
	div.row
		div.col-md-3
		div.col-md-6
			= simple_form_for(@group) do |f|
			  = f.error_notification

			  = f.input :name, label: 'Назва:'
			  = f.label 'Батьківська фондова група: '
			  = f.collection_select :parent_id, Group.order(:name), :id, :name, {include_blank: true}
			  br
			  br
			  = f.input :description, label: 'Опис'
			  = f.file_field :photo, label: 'Фото'
			  br
			  = f.button :submit, value: 'Зберегти'  

app/views/groups/show.html.slim
div.container
  div.row
    div.col-md-3.group-name
      h4
        = @group.name
      = link_to '', edit_group_path(@group), class: 'glyphicon glyphicon-pencil'  
    div.col-md-9
      =render 'shared/breadcrumb', group: @group 
  div.row
    div.col-md-3.submenu-block
      = render 'shared/submenu'
    div.col-md-9
      - unless @exhibits.present?
        div.empty-message.text-center
          p 
            | На даний момент тут нічого немає
            br
            = link_to "Додати експонат", new_exhibit_path, class: 'small-text' if user_signed_in?
      - @exhibits.each do |exh|
        = link_to exh do
          div.exhibit-preview
            h4
              = exh.name
            p
              = exh.dating
            div
              - if exh.photo.present?
                = image_tag exh.photo.url(:thumb)
              - else   
                = image_tag("default_photo.jpg", style: "max-width: 300px; max-height: 220px;")
      div.row
        div.col-md-12        
          = paginate @exhibits
          =render 'shared/breadcrumb', group: @group 