config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :exhibits
  resources :groups
  resources :articles

  namespace :admin do
    resources :users
    resources :exhibits
    resources :groups
    resources :articles
  end

end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    .row
      .col-md-3.footer-groups
        = render "groups/footer_groups"
      .col-md-6.text-center
        p 2016 © Народний історико-краєзнавчий музей «Мостищина»
        p.small Працює на Ruby on Rails 
      .col-md-2.text-center
        img.social-button alt="facebook" src=asset_path('facebook-icon.png') 
        img.social-button  alt="twitter" src=asset_path('twitter-icon.png')   
      .col-md-1.sys-buttons
        - if user_signed_in?
          div
            = link_to '', edit_user_registration_path, class: 'glyphicon glyphicon-user'
          div
            = link_to '', destroy_user_session_path, :method=>'delete', class: 'glyphicon glyphicon-off'
        - else
          div
        	  = link_to '', new_user_session_path, class: 'glyphicon glyphicon-briefcase'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.slim
- if user_signed_in?
  li = link_to '', new_exhibit_path, class: "glyphicon glyphicon-tasks"
  li = link_to '', new_article_path, class: "glyphicon glyphicon-file"
  /li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li= link_to 'Sign in', new_user_session_path
  li= link_to 'Sign up', new_user_registration_path
/- if user_signed_in?
  - if current_user.try(:admin?)
    li= link_to 'Admin', '/admin'
    li= link_to 'Users', users_path

app/views/layouts/_navigation.html.slim
/! Navigation
nav.navbar.navbar-default role="navigation" 
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      /! navbar-brand is hidden on larger screens, but visible when the menu is collapsed
      = link_to 'Музей Мостищина', root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      div.row
        div.col-md-2
        div.col-md-8
          ul.nav.navbar-nav
            = render 'layouts/navigation_links'
            = render 'layouts/nav_links_for_auth' if user_signed_in?
        div.col-md-2
          = form_tag exhibits_path, method: :get, enforce_utf8: false, class: 'form-inline' do
            div.input-group.search-bar
              = text_field_tag 'q', '', placeholder: 'Пошук...', class: 'form-control input-md search-field'
              span.input-group-btn
                = image_submit_tag("search.png", class: 'btn btn-info margin', alt: 'Пошук')
                  i.glyphicon.glyphicon-search

app/views/layouts/_navigation_links.html.slim
li
  = link_to 'Головна', root_path
li
  = link_to 'Фонди', groups_path
li
  = link_to 'Новини', articles_path
li
  = link_to 'Контакти', page_path('contact')

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title = @title.present? ? @title : "Title"
    meta content=("#{content_for?(:description) ? yield(:description) : "My Applicatio2n"}") name="description" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    link href="//fonts.googleapis.com/css?family=Philosopher" rel="stylesheet" type="text/css"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyChJvkG27cUdouHAr4iqFQi6WxF_G5eoZI&libraries=places&v=3"
    = csrf_meta_tags
    /! Custom Fonts 
  body
    = render 'layouts/messages'
    div#header.brand
      div.row
        div.col-md-1
        div.col-md-2 
          = image_tag('logo.png', class: 'site-logo')
        div.col-md-8.title  
          | Адмінка
    /.address-bar м. Мостиська, вулиця Михайла Грушевського, 11
    = render 'layouts/navigation'
    = yield
    = render 'layouts/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title = @title.present? ? @title : "Title"
    meta content=("#{content_for?(:description) ? yield(:description) : "My Applicatio2n"}") name="description" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    link href="//fonts.googleapis.com/css?family=Philosopher" rel="stylesheet" type="text/css"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyChJvkG27cUdouHAr4iqFQi6WxF_G5eoZI&libraries=places&v=3"
    = csrf_meta_tags
    /! Custom Fonts 
  body
    = render 'layouts/messages'
    div#header.brand
      div.row
        div.col-md-1
        div.col-md-2 
          = image_tag('logo.png', class: 'site-logo')
        div.col-md-8.title  
          | Народний історико-краєзнавчий музей «Мостищина» 
    /.address-bar м. Мостиська, вулиця Михайла Грушевського, 11
    = render 'layouts/navigation'
    = yield
    = render 'layouts/footer'